import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNav from "@components/navbar/TopNav/TopNav";
import Navbar from "@components/navbar/MainNav/Navbar";
import Footer from "@components/Footer/Footer";
import { ThemeProvider } from "next-themes";
import { LanguageProvider } from "./Context/LanguageContext";
import NavbarServer from "./components/navbar/MainNav/NavbarServer";


const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Eduka Home page",
  description: "Generated by eduka school management",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

          <LanguageProvider>
          <ThemeProvider
          enableSystem={true}
          attribute="class"
        >
          <TopNav />
          <NavbarServer />
          {children}
          <Footer />
        </ThemeProvider>
        </LanguageProvider>

      </body>
    </html>
  );
}
