import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"
import TopNav from "@components/navbar/TopNav/TopNav";
import Navbar from "@components/navbar/MainNav/Navbar";
import Footer from "@components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Eduka Home page",
  description: "Generated by eduka school management",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopNav />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
